name: test-hook

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.0'
      - name: Build and run tests
        run: |
          gem install bundler
          bundle install
          rspec spec/
